telegram:
  token: "8393627945:AAHkKTFifa26510j33mDC8jJBnsQPUhK-VQ"
  channel_id: -1002962445949  # Channel ID: upload files (@uploadrobotfile)
  group_link: "https://t.me/rapexa_gap"  # Group link

database:
  host: "localhost"
  port: 3306
  user: "appuser"
  password: "app_password"
  name: "telegram_bot"

video:
  message_id: 2  # Default message ID from channel

server:
  url: "http://localhost:8081"  # Your server URL for serving uploaded files
  port: "8081"  # Port for file server (separate from main app)

sms:
  apikey: "OWYzZmNmNGYtZjEzMi00YjIyLWJhMzgtYmFjZjQ3NWFmMjIxMDcwZGE0ZWMwZDcyYzAxNjcxZDlkMjU0MzAzZmJhMGY="
  from_number: "+983000505"
  base_url: "https://api2.ippanel.com/api/v1"
  patterns:
    registration: "kii5iwrowp477q4"