telegram:
  token: "8393627945:AAHkKTFifa26510j33mDC8jJBnsQPUhK-VQ"
  channel_id: -1002962445949  # Channel ID: upload files (@uploadrobotfile)
  group_link: "https://t.me/+AGayy6YDChBmMjM0"  # Group link
  mandatory_channel_id: -1001976057034  # Mandatory channel ID (@hoseinmehri_ir1)
  mandatory_channel_username: "@hoseinmehri_ir1"  # Mandatory channel username

database:
  host: "localhost"
  port: 3306
  user: "appuser"
  password: "app_password"
  name: "telegram_bot"

video:
  message_id: 2  # Default message ID from channel

server:
  url: "http://localhost:8081"  # Your server URL for serving uploaded files
  port: "8081"  # Port for file server (separate from main app)

sms:
  apikey: "OWZlN2Q5NDMtYjY1OS00MzZmLTk5MTgtNzgxNmFmMDMxMzY4OTBhZjU2NWZlNjViMzNhODliMWQyOGJjYWUzMzNiNTQ="
  from_number: "+983000505"
  base_url: "https://api2.ippanel.com/api/v1"
  patterns:
    registration: "0fvxstcgdfasjhu"